### ISSUE TITLE
Cartopy and Modules Error

### ISSUE THREAD

**Issue by gkb999** [Dan-Boat/PyESD#2]
Hi Thanks for following up on installation.
I'm now, able to install pyESD
yet, the modules aren't imported.
It says "No Module" error even after Cartopy being installed.
![image](https://github.com/Dan-Boat/PyESD/assets/7091088/bb100d8c-348a-4f9c-8c99-edaa3adc6e28)

![image](https://github.com/Dan-Boat/PyESD/assets/7091088/ce6b8bde-b42d-4eea-83d0-da2cadc9e1e8)

I'm assuming this is windows compatible!

**Comment by Dan-Boat** [comment]
Installing cartopy on windows is sometimes complicated. I did not add it to the dependecies in the setup for the pip installation because of that. I will modify the code to only use cartopy when its properly installed and needed. The modeling framework does not require cartopy. 

Things to troubleshoot:
1. Try importing cartopy directly when you activate the environment. If its successful, try to use it with a simple example to see if it works well. Otherwise trying installing it with 
`conda install -c conda-forge cartopy`

2. You can install the pyESD package in edit model with the -e flag, then comment out the import cartopy line in the ESD_utils

Please update me when you try this while I try to fix the package. Thanks for the raising this issue

**Comment by gkb999** [comment]
Hi Dan, Sorry for re-opening, I couldn't actually check when you asked me to.
But this is strange error here.
Installing 
```
from pyESD.standardizer import MonthlyStandardizer, StandardScaling
from pyESD.ESD_utils import store_pickle, store_csv
from pyESD.splitter import KFold
from pyESD.ESD_utils import Dataset

import pandas as pd 
``` 
shows no error.
Where as:
```
from pyESD.Weatherstation import read_weatherstationnames
```
gives the following error:

```
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
     18 try:
---> 19     from standardizer import MonthlyStandardizer, NoStandardizer
     20     from feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection

ModuleNotFoundError: No module named 'standardizer'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
     18     from .standardizer import MonthlyStandardizer
---> 19     from .predictand import PredictandTimeseries
     20     from .teleconnections import NAO, SCAN, EA, EAWR, MEI

~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
     28     from .feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection
---> 29     from .models import Regressors
     30     from .ensemble_models import EnsembleRegressor

~\AppData\Roaming\Python\Python39\site-packages\pyESD\models.py in <module>
     24 from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, BaggingRegressor, AdaBoostRegressor
---> 25 from sklearn.ensemble import HistGradientBoostingRegressor, GradientBoostingRegressor
     26 from sklearn.model_selection import cross_val_score, cross_validate, cross_val_predict

ImportError: cannot import name 'HistGradientBoostingRegressor' from 'sklearn.ensemble' (C:\Windows\Anaconda3-2021.11\lib\site-packages\sklearn\ensemble\__init__.py)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
     24 try:
---> 25     from .StationOperator import StationOperator
     26 except:

~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
     21 except:
---> 22     from Predictor_Generator import *
     23     from standardizer import MonthlyStandardizer

ModuleNotFoundError: No module named 'Predictor_Generator'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3120/1331661768.py in <module>
----> 1 from pyESD.Weatherstation import read_weatherstationnames

~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
     25     from .StationOperator import StationOperator
     26 except:
---> 27     from StationOperator import StationOperator
     28 
     29 

ModuleNotFoundError: No module named 'StationOperator'
```
For a very long time it was "Cartopy"
Now it is the one mentioned above, and the one below:
```
from pyESD.Weatherstation import read_station_csv
```
Error:
```
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
     18 try:
---> 19     from standardizer import MonthlyStandardizer, NoStandardizer
     20     from feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection

ModuleNotFoundError: No module named 'standardizer'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
     18     from .standardizer import MonthlyStandardizer
---> 19     from .predictand import PredictandTimeseries
     20     from .teleconnections import NAO, SCAN, EA, EAWR, MEI

~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
     28     from .feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection
---> 29     from .models import Regressors
     30     from .ensemble_models import EnsembleRegressor

~\AppData\Roaming\Python\Python39\site-packages\pyESD\models.py in <module>
     24 from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, BaggingRegressor, AdaBoostRegressor
---> 25 from sklearn.ensemble import HistGradientBoostingRegressor, GradientBoostingRegressor
     26 from sklearn.model_selection import cross_val_score, cross_validate, cross_val_predict

ImportError: cannot import name 'HistGradientBoostingRegressor' from 'sklearn.ensemble' (C:\Windows\Anaconda3-2021.11\lib\site-packages\sklearn\ensemble\__init__.py)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
     24 try:
---> 25     from .StationOperator import StationOperator
     26 except:

~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
     21 except:
---> 22     from Predictor_Generator import *
     23     from standardizer import MonthlyStandardizer

ModuleNotFoundError: No module named 'Predictor_Generator'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3120/1431239707.py in <module>
----> 1 from pyESD.Weatherstation import read_station_csv

~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
     25     from .StationOperator import StationOperator
     26 except:
---> 27     from StationOperator import StationOperator
     28 
     29 

ModuleNotFoundError: No module named 'StationOperator'
```

Is it something to do with station data?

Also, do I need to download ERA5 data manually and use that for ERA5_Direc?

**Comment by gkb999** [comment]
> Hi Dan, Sorry for re-opening, I couldn't actually check when you asked me to. But this is strange error here. Installing
> 
> ```
> from pyESD.standardizer import MonthlyStandardizer, StandardScaling
> from pyESD.ESD_utils import store_pickle, store_csv
> from pyESD.splitter import KFold
> from pyESD.ESD_utils import Dataset
> 
> import pandas as pd 
> ```
> 
> shows no error. Where as:
> 
> ```
> from pyESD.Weatherstation import read_weatherstationnames
> ```
> 
> gives the following error:
> 
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
>      18 try:
> ---> 19     from standardizer import MonthlyStandardizer, NoStandardizer
>      20     from feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection
> 
> ModuleNotFoundError: No module named 'standardizer'
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError                               Traceback (most recent call last)
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
>      18     from .standardizer import MonthlyStandardizer
> ---> 19     from .predictand import PredictandTimeseries
>      20     from .teleconnections import NAO, SCAN, EA, EAWR, MEI
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
>      28     from .feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection
> ---> 29     from .models import Regressors
>      30     from .ensemble_models import EnsembleRegressor
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\models.py in <module>
>      24 from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, BaggingRegressor, AdaBoostRegressor
> ---> 25 from sklearn.ensemble import HistGradientBoostingRegressor, GradientBoostingRegressor
>      26 from sklearn.model_selection import cross_val_score, cross_validate, cross_val_predict
> 
> ImportError: cannot import name 'HistGradientBoostingRegressor' from 'sklearn.ensemble' (C:\Windows\Anaconda3-2021.11\lib\site-packages\sklearn\ensemble\__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> ModuleNotFoundError                       Traceback (most recent call last)
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
>      24 try:
> ---> 25     from .StationOperator import StationOperator
>      26 except:
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
>      21 except:
> ---> 22     from Predictor_Generator import *
>      23     from standardizer import MonthlyStandardizer
> 
> ModuleNotFoundError: No module named 'Predictor_Generator'
> 
> During handling of the above exception, another exception occurred:
> 
> ModuleNotFoundError                       Traceback (most recent call last)
> ~\AppData\Local\Temp/ipykernel_3120/1331661768.py in <module>
> ----> 1 from pyESD.Weatherstation import read_weatherstationnames
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
>      25     from .StationOperator import StationOperator
>      26 except:
> ---> 27     from StationOperator import StationOperator
>      28 
>      29 
> 
> ModuleNotFoundError: No module named 'StationOperator'
> ```
> 
> For a very long time it was "Cartopy" Now it is the one mentioned above, and the one below:
> 
> ```
> from pyESD.Weatherstation import read_station_csv
> ```
> 
> Error:
> 
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
>      18 try:
> ---> 19     from standardizer import MonthlyStandardizer, NoStandardizer
>      20     from feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection
> 
> ModuleNotFoundError: No module named 'standardizer'
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError                               Traceback (most recent call last)
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
>      18     from .standardizer import MonthlyStandardizer
> ---> 19     from .predictand import PredictandTimeseries
>      20     from .teleconnections import NAO, SCAN, EA, EAWR, MEI
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\predictand.py in <module>
>      28     from .feature_selection import RecursiveFeatureElimination, TreeBasedSelection, SequentialFeatureSelection
> ---> 29     from .models import Regressors
>      30     from .ensemble_models import EnsembleRegressor
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\models.py in <module>
>      24 from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, BaggingRegressor, AdaBoostRegressor
> ---> 25 from sklearn.ensemble import HistGradientBoostingRegressor, GradientBoostingRegressor
>      26 from sklearn.model_selection import cross_val_score, cross_validate, cross_val_predict
> 
> ImportError: cannot import name 'HistGradientBoostingRegressor' from 'sklearn.ensemble' (C:\Windows\Anaconda3-2021.11\lib\site-packages\sklearn\ensemble\__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> ModuleNotFoundError                       Traceback (most recent call last)
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
>      24 try:
> ---> 25     from .StationOperator import StationOperator
>      26 except:
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\StationOperator.py in <module>
>      21 except:
> ---> 22     from Predictor_Generator import *
>      23     from standardizer import MonthlyStandardizer
> 
> ModuleNotFoundError: No module named 'Predictor_Generator'
> 
> During handling of the above exception, another exception occurred:
> 
> ModuleNotFoundError                       Traceback (most recent call last)
> ~\AppData\Local\Temp/ipykernel_3120/1431239707.py in <module>
> ----> 1 from pyESD.Weatherstation import read_station_csv
> 
> ~\AppData\Roaming\Python\Python39\site-packages\pyESD\Weatherstation.py in <module>
>      25     from .StationOperator import StationOperator
>      26 except:
> ---> 27     from StationOperator import StationOperator
>      28 
>      29 
> 
> ModuleNotFoundError: No module named 'StationOperator'
> ```
> 
> Is it something to do with station data?
> 
> Also, do I need to download ERA5 data manually and use that for ERA5_Direc?

@Dan-Boat
